"""empty message

Revision ID: 100bec6d3ea
Revises: 5726cd11a55
Create Date: 2015-02-15 02:08:42.778705

"""

# revision identifiers, used by Alembic.
revision = '100bec6d3ea'
down_revision = '5726cd11a55'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
