"""empty message

Revision ID: 431fbc7711
Revises: 5a322304ee7
Create Date: 2015-02-10 15:20:30.230749

"""

# revision identifiers, used by Alembic.
revision = '431fbc7711'
down_revision = '5a322304ee7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=50), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    ### end Alembic commands ###
