"""empty message

Revision ID: 5726cd11a55
Revises: 51311df0a3
Create Date: 2015-02-14 17:09:49.131539

"""

# revision identifiers, used by Alembic.
revision = '5726cd11a55'
down_revision = '51311df0a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posting', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('posting', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('fname', sa.String(length=40), nullable=True))
    op.add_column('users', sa.Column('lname', sa.String(length=40), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'lname')
    op.drop_column('users', 'fname')
    op.drop_column('posting', 'price')
    op.drop_column('posting', 'date')
    ### end Alembic commands ###
