"""empty message

Revision ID: 5a322304ee7
Revises: 3e854797161
Create Date: 2015-02-10 14:15:31.292377

"""

# revision identifiers, used by Alembic.
revision = '5a322304ee7'
down_revision = '3e854797161'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=50), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    ### end Alembic commands ###
